version: '3'

services:
  app:
    container_name: app
    build: ./
    ports:
      - 5000:5000
  redis:
    container_name: redis-container
    image: redis:latest
    expose:
      - '6379'
    ports:
     - '6379:6379'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
